### PR TITLE
Added list of presets, closes #289

### LINKED ISSUE #289: Should we mention the most popular remark presets somewhere?
Link to most popular presets on NPM?

<https://www.npmjs.com/search?q=remark-preset>

Maybe include this in docs?

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by wooorm** [comment]
Thanks @niftylettuce!

Hmm, now I think about it, I dunno 🤔

All presets are currently very personal: my personal preset, and some company presets for their style guides: those represent styles used by the owners, highly specific, and probably not very open to contributions from others. Presets are also cheap to create: people should look to other presets for inspiration and then probably create their own.

The list of plugins is lightly curated, contains working and maintained projects that are useful, open to contributions, with quite some hard work into them.

Maybe a link to npm, that searches for `remark-preset` instead, does the job better?

**Comment by niftylettuce** [comment]
Done, updated my PR

**Comment by wooorm** [comment]
Awesome, super, great! 👍

**Comment by wooorm** [comment]
Thanks a bunch @niftylettuce!

**Pull request merged**
