### PR TITLE
Add heading-gap, word-wrap to plugins list.

### PR DESCRIPTION
**Pull request by ben-eb**

### CODE REVIEW

**Comment by wooorm** [comment]
@ben-eb P.S. This is blocked because `remark-word-wrap` does not yet produce desirable results (as far as I know?)

**Comment by wooorm** [comment]
Ok I’m including `heading-gap` now, can you open a new PR when `word-wrap` is done?

**Comment by ben-eb** [comment]
OK, no worries; probably won't be soon though. :smile:

**Comment by wooorm** [comment]
:+1:

**Pull request closed without merging**
