### PR TITLE
Added a plugin

### PR DESCRIPTION
**Pull request by RichardLitt**
Noticed these were not here.

### CODE REVIEW

**Comment by wooorm** [comment]
Cool, thanks! 👍 

One thing though, could you move the remark-lint rule over to [it’s own list of rules](https://github.com/wooorm/remark-lint#list-of-external-rules)?

**Comment by RichardLitt** [comment]
Removed. Done!

**Comment by wooorm** [comment]
Did you forget to push? I’m still seeing the lint rule (Maybe I was unclear, sorry! 😧)

**Comment by RichardLitt** [comment]
huh. Weird. Think I was in the wrong window or something. Fixed. :)

**Comment by wooorm** [comment]
Perfect, thanks! ❤️

**Pull request merged**
